services:
  - type: web
    name: webwatch
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GCP_JSON
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"

  - type: web
    name: stresschecker
    runtime: python
    rootDir: stresschecker
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEMO_MODE
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.0"
